name: Gerar Dados

on:
  schedule:  # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Trabalhos para atualizar dados
    runs-on: ubuntu-latest

    steps:
      # Animação de cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: cmarih
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
